---
openapi: 3.0.0
info:
  title: Super Cars API 
  description: Cars CRUD API using python flask
  version: 1.0.0
  contact:
    name: API support
    email: birnesh711@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: "/"
    description: "Local server"
  - url: "/dev"
    description: "development server"
tags:
  - name: Car CRUD
  - name: Manufacturer CRUD
paths:
  /cars:
    get:
      summary: Returns all Cars 
      description: Gives all the cars that has been registered
      tags:
        - Car CRUD
      operationId: getAllCars
      responses:
        "200":
          description: A list of Cars
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/carItemResponse"
      
  /car/{id}:
    get:
      summary: Retrieves a car
      description: Finds a car with a specific id
      tags:
        - Car CRUD
      operationId: getACar
      parameters:
        - name: id
          in: path
          description: ID of the car that needs to be retrieved
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: data retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/carItemResponse"
  /manufacturers:
    get:
      summary: Returns All manufacturers
      description: Gives a list of manufacturers objects
      tags:
        - Manufacturer CRUD
      operationId: getAllManufacturers
      responses:
        "200":
          description: A list of manufacturers
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/manufacturerItemResponse"
    post:
      summary: Post a Manufucture record
      description: Enables to post a Manufacturer object
      tags:
        - Manufacturer CRUD
      operationId: postAManufacturer
      requestBody:
        description: Manufacturer post requestBody
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/manufacturerItemPostRequest"
      responses:
        "201":
          description: Manufacturer post successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/manufacturerItemResponse"


  /manufacturer/{id}:
    get:
      summary: Retrieves a Manufacturer
      description: Finds a Manufacturer with the given ID
      tags:
        - Manufacturer CRUD
      operationId: getAManufacturer
      parameters:
        - name: id
          in: path
          description: ID of the manufacturer that needs to be retrieved
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: retrieved successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/manufacturerItemResponse"
    delete:
      summary: Remove a single Manufacturer
      description: Removes the record permanently
      tags:
        - Manufacturer CRUD
      operationId: deleteAManufacturer
      parameters:
        - name: id
          in: path
          description: ID of the manufacturer record that needs to be removed
          required: true
          schema: 
            type: integer
      responses:
        "200":
          description: The delete request is successfull
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/manufacturerItemResponse"


                

components:
  schemas:
    carItemResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        manufacturer_id:
          type: integer
          format: int32
        launched_year:
          type: integer
          format: int32
        top_speed:
          type: integer
          format: int32
        engine_type:
          type: string
        max_horse_power:
          type: integer
          format: int32
        zero_to_hundred:
          type: integer
          format: int32
        manufacturer:
          type: string
    manufacturerItemResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        head_quarter:
          type: string
        founder:
          type: string
        established_year:
          type: integer
          format: int32
    manufacturerItemPostRequest:
      type: object
      required:
        - name
        - head_quarter
        - founder
        - established_year
      properties:
        name:
          type: string
        head_quarter:
          type: string
        founder:
          type: string
        established_year:
          type: integer
          format: int32
